### ISSUE TITLE
Setting an objective to display on the sidebar of a team color causes packet errors, resulting in the server being impossible to connect to.

### ISSUE THREAD

**Issue by OrangeCatUnderscore** [NEZNAMY/VelocityScoreboardAPI#3]
#### Description:

Setting an objective to display on the sidebar of a team color causes packet errors, resulting in the server being impossible to connect to.

#### Environment:

Proxy: Velocity 3.4.0 build 449, VelocityScoreboardAPI 1.0.4 is the only plugin installed.
Backend: Paper 1.21.1 build 130, no plugins installed.

#### Reproduction steps:

1. Connect to the backend server.
2. Ensure you have operator permissions.
3. Run `/scoreboard objectives add test dummy`.
4. Run `/scoreboard objectives setdisplay sidebar.team.<color> test`, any color works.

#### Result:

If you follow the above steps, you and any other players connected to the same backend will be kicked.  Attempting to log in afterwards has the same result.

On your client, you'll see this:

![2024-10-30_19 34 44](https://github.com/user-attachments/assets/e79168af-c065-4b1f-8949-b48547cc44f1)

In your Velocity console, you'll see this:
```
[20:48:21 ERROR]: [server connection] OrangeCat_ -> main: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@c3dc485
com.velocitypowered.proxy.util.except.QuietRuntimeException: A packet did not decode successfully (invalid data). For more information, launch Velocity with -Dvelocity.packet-decode-logging=true to see more.
```

If Velocity is launched with -Dvelocity.packet-decode-logging=true, you'll see this:
```
[20:50:01 ERROR]: [server connection] OrangeCat_ -> main: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@46f12595
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.scoreboard.DisplayObjectivePacket Direction CLIENTBOUND Protocol 1.21 State PLAY ID 57
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:130) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:85) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:60) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:455) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at com.velocitypowered.proxy.protocol.packet.scoreboard.DisplayObjectivePacket.decode(DisplayObjectivePacket.java:65) ~[?:?]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:83) ~[velocity-3.4.0-SNAPSHOT-449.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
        ... 30 more
```

**Comment by NEZNAMY** [comment]
Try new build from [actions](https://github.com/NEZNAMY/VelocityScoreboardAPI/actions).

**Comment by OrangeCatUnderscore** [comment]
Seems to be fixed, thanks
