### ISSUE TITLE
1.8.9 Players Cannot Connect (No enum constant com.velocitypowered.api.scoreboard.HealthDisplay)

### ISSUE THREAD

**Issue by xEricL** [NEZNAMY/VelocityScoreboardAPI#7]
This issue seems to only affect players on 1.8.9; 1.21.1 connect just fine.

```
[10:26:21] [Netty epoll Boss #0/INFO] [com.velocitypowered.proxy.network.ConnectionManager]: Listening on /[0:0:0:0:0:0:0:0]:25565
[10:26:21] [main/INFO] [com.velocitypowered.proxy.Velocity]: Done (2.16s)!
[10:26:25] [Netty epoll Worker #30/INFO] [com.velocitypowered.proxy.connection.client.AuthSessionHandler]: [connected player] yoloswag58 (<ip address withheld>) has connected
[10:26:25] [Netty epoll Worker #30/INFO] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] yoloswag58 -> hub has connected
[10:26:25] [Netty epoll Worker #30/ERROR] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] yoloswag58 -> hub: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@511858ea
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.scoreboard.ObjectivePacket Direction CLIENTBOUND Protocol 1.8 State PLAY ID 3b
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:130) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:85) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:60) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:455) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant com.velocitypowered.api.scoreboard.HealthDisplay.
	at java.base/java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at com.velocitypowered.api.scoreboard.HealthDisplay.valueOf(HealthDisplay.java:29) ~[?:?]
	at com.velocitypowered.proxy.protocol.packet.scoreboard.ObjectivePacket.decode(ObjectivePacket.java:101) ~[?:?]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:83) ~[velocity-3.4.0-SNAPSHOT-452.jar:3.4.0-SNAPSHOT (git-a33f2d1a-b452)]
	... 30 more
	```

**Comment by NEZNAMY** [comment]
We will need steps to reproduce. Something is encoding a packet in a way even vanilla doesn't. I took a look at bungeecord's packet decoder and it looks like it would also throw an error in this case.

**Comment by xEricL** [comment]
It appears the problem was [Simple Score](https://modrinth.com/plugin/simplescore). I disabled it and the problem went away. Strange.

Might've been this https://github.com/TheRainTrain/SimpleScore?tab=readme-ov-file#known-issues

**Comment by xEricL** [comment]
Decided to just use TAB for my scoreboard instead. Works without issue.

**Comment by NEZNAMY** [comment]
After investigating I can confirm it's caused by SimpleScore using ProtocolLib's API incorrectly to encode packets, causing this issue. It also happens on BungeeCord. I have added a check to avoid the error.
